/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as appSettingsRouteImport } from './routes/(app)/settings'
import { Route as appProfileRouteImport } from './routes/(app)/profile'
import { Route as appMatchesRouteImport } from './routes/(app)/matches'
import { Route as appFeedRouteImport } from './routes/(app)/feed'
import { Route as appChatsRouteImport } from './routes/(app)/chats'
import { Route as appChatChatIdRouteImport } from './routes/(app)/chat.$chatId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const appSettingsRoute = appSettingsRouteImport.update({
  id: '/(app)/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const appProfileRoute = appProfileRouteImport.update({
  id: '/(app)/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const appMatchesRoute = appMatchesRouteImport.update({
  id: '/(app)/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const appFeedRoute = appFeedRouteImport.update({
  id: '/(app)/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const appChatsRoute = appChatsRouteImport.update({
  id: '/(app)/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const appChatChatIdRoute = appChatChatIdRouteImport.update({
  id: '/(app)/chat/$chatId',
  path: '/chat/$chatId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chats': typeof appChatsRoute
  '/feed': typeof appFeedRoute
  '/matches': typeof appMatchesRoute
  '/profile': typeof appProfileRoute
  '/settings': typeof appSettingsRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/chat/$chatId': typeof appChatChatIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chats': typeof appChatsRoute
  '/feed': typeof appFeedRoute
  '/matches': typeof appMatchesRoute
  '/profile': typeof appProfileRoute
  '/settings': typeof appSettingsRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/chat/$chatId': typeof appChatChatIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)/chats': typeof appChatsRoute
  '/(app)/feed': typeof appFeedRoute
  '/(app)/matches': typeof appMatchesRoute
  '/(app)/profile': typeof appProfileRoute
  '/(app)/settings': typeof appSettingsRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(app)/chat/$chatId': typeof appChatChatIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chats'
    | '/feed'
    | '/matches'
    | '/profile'
    | '/settings'
    | '/login'
    | '/signup'
    | '/chat/$chatId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chats'
    | '/feed'
    | '/matches'
    | '/profile'
    | '/settings'
    | '/login'
    | '/signup'
    | '/chat/$chatId'
  id:
    | '__root__'
    | '/'
    | '/(app)/chats'
    | '/(app)/feed'
    | '/(app)/matches'
    | '/(app)/profile'
    | '/(app)/settings'
    | '/(auth)/login'
    | '/(auth)/signup'
    | '/(app)/chat/$chatId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appChatsRoute: typeof appChatsRoute
  appFeedRoute: typeof appFeedRoute
  appMatchesRoute: typeof appMatchesRoute
  appProfileRoute: typeof appProfileRoute
  appSettingsRoute: typeof appSettingsRoute
  authLoginRoute: typeof authLoginRoute
  authSignupRoute: typeof authSignupRoute
  appChatChatIdRoute: typeof appChatChatIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/settings': {
      id: '/(app)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof appSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/profile': {
      id: '/(app)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof appProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/matches': {
      id: '/(app)/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof appMatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/feed': {
      id: '/(app)/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof appFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/chats': {
      id: '/(app)/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof appChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/chat/$chatId': {
      id: '/(app)/chat/$chatId'
      path: '/chat/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof appChatChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appChatsRoute: appChatsRoute,
  appFeedRoute: appFeedRoute,
  appMatchesRoute: appMatchesRoute,
  appProfileRoute: appProfileRoute,
  appSettingsRoute: appSettingsRoute,
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
  appChatChatIdRoute: appChatChatIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
