/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UiKitRouteImport } from './routes/ui-kit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as appSettingsRouteImport } from './routes/(app)/settings'
import { Route as appProfileRouteImport } from './routes/(app)/profile'
import { Route as appMatchesRouteImport } from './routes/(app)/matches'
import { Route as appFeedRouteImport } from './routes/(app)/feed'
import { Route as appChatsRouteImport } from './routes/(app)/chats'
import { Route as appAgentsRouteImport } from './routes/(app)/agents'
import { Route as appAgentPersonaRouteImport } from './routes/(app)/agent-persona'
import { Route as appProfileIndexRouteImport } from './routes/(app)/profile.index'
import { Route as appAgentsIndexRouteImport } from './routes/(app)/agents.index'
import { Route as authAuthSuccessRouteImport } from './routes/(auth)/auth/success'
import { Route as appProfileEditRouteImport } from './routes/(app)/profile.edit'
import { Route as appChatChatIdRouteImport } from './routes/(app)/chat.$chatId'
import { Route as appAgentsEncounterIdRouteImport } from './routes/(app)/agents.$encounterId'

const UiKitRoute = UiKitRouteImport.update({
  id: '/ui-kit',
  path: '/ui-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const appSettingsRoute = appSettingsRouteImport.update({
  id: '/(app)/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const appProfileRoute = appProfileRouteImport.update({
  id: '/(app)/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const appMatchesRoute = appMatchesRouteImport.update({
  id: '/(app)/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const appFeedRoute = appFeedRouteImport.update({
  id: '/(app)/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const appChatsRoute = appChatsRouteImport.update({
  id: '/(app)/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const appAgentsRoute = appAgentsRouteImport.update({
  id: '/(app)/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const appAgentPersonaRoute = appAgentPersonaRouteImport.update({
  id: '/(app)/agent-persona',
  path: '/agent-persona',
  getParentRoute: () => rootRouteImport,
} as any)
const appProfileIndexRoute = appProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appProfileRoute,
} as any)
const appAgentsIndexRoute = appAgentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appAgentsRoute,
} as any)
const authAuthSuccessRoute = authAuthSuccessRouteImport.update({
  id: '/(auth)/auth/success',
  path: '/auth/success',
  getParentRoute: () => rootRouteImport,
} as any)
const appProfileEditRoute = appProfileEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => appProfileRoute,
} as any)
const appChatChatIdRoute = appChatChatIdRouteImport.update({
  id: '/(app)/chat/$chatId',
  path: '/chat/$chatId',
  getParentRoute: () => rootRouteImport,
} as any)
const appAgentsEncounterIdRoute = appAgentsEncounterIdRouteImport.update({
  id: '/$encounterId',
  path: '/$encounterId',
  getParentRoute: () => appAgentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ui-kit': typeof UiKitRoute
  '/agent-persona': typeof appAgentPersonaRoute
  '/agents': typeof appAgentsRouteWithChildren
  '/chats': typeof appChatsRoute
  '/feed': typeof appFeedRoute
  '/matches': typeof appMatchesRoute
  '/profile': typeof appProfileRouteWithChildren
  '/settings': typeof appSettingsRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/agents/$encounterId': typeof appAgentsEncounterIdRoute
  '/chat/$chatId': typeof appChatChatIdRoute
  '/profile/edit': typeof appProfileEditRoute
  '/auth/success': typeof authAuthSuccessRoute
  '/agents/': typeof appAgentsIndexRoute
  '/profile/': typeof appProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ui-kit': typeof UiKitRoute
  '/agent-persona': typeof appAgentPersonaRoute
  '/chats': typeof appChatsRoute
  '/feed': typeof appFeedRoute
  '/matches': typeof appMatchesRoute
  '/settings': typeof appSettingsRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/agents/$encounterId': typeof appAgentsEncounterIdRoute
  '/chat/$chatId': typeof appChatChatIdRoute
  '/profile/edit': typeof appProfileEditRoute
  '/auth/success': typeof authAuthSuccessRoute
  '/agents': typeof appAgentsIndexRoute
  '/profile': typeof appProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ui-kit': typeof UiKitRoute
  '/(app)/agent-persona': typeof appAgentPersonaRoute
  '/(app)/agents': typeof appAgentsRouteWithChildren
  '/(app)/chats': typeof appChatsRoute
  '/(app)/feed': typeof appFeedRoute
  '/(app)/matches': typeof appMatchesRoute
  '/(app)/profile': typeof appProfileRouteWithChildren
  '/(app)/settings': typeof appSettingsRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(app)/agents/$encounterId': typeof appAgentsEncounterIdRoute
  '/(app)/chat/$chatId': typeof appChatChatIdRoute
  '/(app)/profile/edit': typeof appProfileEditRoute
  '/(auth)/auth/success': typeof authAuthSuccessRoute
  '/(app)/agents/': typeof appAgentsIndexRoute
  '/(app)/profile/': typeof appProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ui-kit'
    | '/agent-persona'
    | '/agents'
    | '/chats'
    | '/feed'
    | '/matches'
    | '/profile'
    | '/settings'
    | '/login'
    | '/signup'
    | '/agents/$encounterId'
    | '/chat/$chatId'
    | '/profile/edit'
    | '/auth/success'
    | '/agents/'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ui-kit'
    | '/agent-persona'
    | '/chats'
    | '/feed'
    | '/matches'
    | '/settings'
    | '/login'
    | '/signup'
    | '/agents/$encounterId'
    | '/chat/$chatId'
    | '/profile/edit'
    | '/auth/success'
    | '/agents'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/ui-kit'
    | '/(app)/agent-persona'
    | '/(app)/agents'
    | '/(app)/chats'
    | '/(app)/feed'
    | '/(app)/matches'
    | '/(app)/profile'
    | '/(app)/settings'
    | '/(auth)/login'
    | '/(auth)/signup'
    | '/(app)/agents/$encounterId'
    | '/(app)/chat/$chatId'
    | '/(app)/profile/edit'
    | '/(auth)/auth/success'
    | '/(app)/agents/'
    | '/(app)/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UiKitRoute: typeof UiKitRoute
  appAgentPersonaRoute: typeof appAgentPersonaRoute
  appAgentsRoute: typeof appAgentsRouteWithChildren
  appChatsRoute: typeof appChatsRoute
  appFeedRoute: typeof appFeedRoute
  appMatchesRoute: typeof appMatchesRoute
  appProfileRoute: typeof appProfileRouteWithChildren
  appSettingsRoute: typeof appSettingsRoute
  authLoginRoute: typeof authLoginRoute
  authSignupRoute: typeof authSignupRoute
  appChatChatIdRoute: typeof appChatChatIdRoute
  authAuthSuccessRoute: typeof authAuthSuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ui-kit': {
      id: '/ui-kit'
      path: '/ui-kit'
      fullPath: '/ui-kit'
      preLoaderRoute: typeof UiKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/settings': {
      id: '/(app)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof appSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/profile': {
      id: '/(app)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof appProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/matches': {
      id: '/(app)/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof appMatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/feed': {
      id: '/(app)/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof appFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/chats': {
      id: '/(app)/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof appChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/agents': {
      id: '/(app)/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof appAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/agent-persona': {
      id: '/(app)/agent-persona'
      path: '/agent-persona'
      fullPath: '/agent-persona'
      preLoaderRoute: typeof appAgentPersonaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/profile/': {
      id: '/(app)/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof appProfileIndexRouteImport
      parentRoute: typeof appProfileRoute
    }
    '/(app)/agents/': {
      id: '/(app)/agents/'
      path: '/'
      fullPath: '/agents/'
      preLoaderRoute: typeof appAgentsIndexRouteImport
      parentRoute: typeof appAgentsRoute
    }
    '/(auth)/auth/success': {
      id: '/(auth)/auth/success'
      path: '/auth/success'
      fullPath: '/auth/success'
      preLoaderRoute: typeof authAuthSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/profile/edit': {
      id: '/(app)/profile/edit'
      path: '/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof appProfileEditRouteImport
      parentRoute: typeof appProfileRoute
    }
    '/(app)/chat/$chatId': {
      id: '/(app)/chat/$chatId'
      path: '/chat/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof appChatChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/agents/$encounterId': {
      id: '/(app)/agents/$encounterId'
      path: '/$encounterId'
      fullPath: '/agents/$encounterId'
      preLoaderRoute: typeof appAgentsEncounterIdRouteImport
      parentRoute: typeof appAgentsRoute
    }
  }
}

interface appAgentsRouteChildren {
  appAgentsEncounterIdRoute: typeof appAgentsEncounterIdRoute
  appAgentsIndexRoute: typeof appAgentsIndexRoute
}

const appAgentsRouteChildren: appAgentsRouteChildren = {
  appAgentsEncounterIdRoute: appAgentsEncounterIdRoute,
  appAgentsIndexRoute: appAgentsIndexRoute,
}

const appAgentsRouteWithChildren = appAgentsRoute._addFileChildren(
  appAgentsRouteChildren,
)

interface appProfileRouteChildren {
  appProfileEditRoute: typeof appProfileEditRoute
  appProfileIndexRoute: typeof appProfileIndexRoute
}

const appProfileRouteChildren: appProfileRouteChildren = {
  appProfileEditRoute: appProfileEditRoute,
  appProfileIndexRoute: appProfileIndexRoute,
}

const appProfileRouteWithChildren = appProfileRoute._addFileChildren(
  appProfileRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UiKitRoute: UiKitRoute,
  appAgentPersonaRoute: appAgentPersonaRoute,
  appAgentsRoute: appAgentsRouteWithChildren,
  appChatsRoute: appChatsRoute,
  appFeedRoute: appFeedRoute,
  appMatchesRoute: appMatchesRoute,
  appProfileRoute: appProfileRouteWithChildren,
  appSettingsRoute: appSettingsRoute,
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
  appChatChatIdRoute: appChatChatIdRoute,
  authAuthSuccessRoute: authAuthSuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
